version: '3'
services:
  producer:
    build: .
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./src:/code


  zookeeper:
    image: jplock/zookeeper:3.4.6
    ports:
      - "2181"

  kafka:
    image: ches/kafka:0.10.1.0
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ZOOKEEPER_IP=zookeeper
      - KAFKA_PORT=9092
      - KAFKA_ADVERTISED_PORT=9092
    extra_hosts:
      - "kafka:127.0.0.1"

